### ISSUE TITLE
Some of the visualisation options may not work

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-server-py#192]
We have a list of possible visualisations in the `visualisations.ipynb` notebook (in the examples folder), but @rhoslynroebuck found that some of these may not be working correctly. This may be a non-issue, but good to check anyway.

**Comment by ludovicaisa** [comment]
Cartoon rendering have issues and here is what I found out with running the protein-ligand systems singularly.

1. When connecting a VR client for the first time the protein rendering work but when restarting the simulation (same server) the protein loose quickly its shape and becomes just a white string.
2.  ligands may be there or not as well the interaction by the controllers can work out or not; when it's not, I tried to disconnect and reconnect the vrclient and the ligand appear again and the interaction could work again.
3. Cartoon rendering of APK passthorugh works slightly different the other: it doesn't have reference atoms (dots) along the protein.

I leave this link with videos I have recorded cheching the rendering, the interaction and the ligand's presence for those three systems, [here](https://nubeusc-my.sharepoint.com/:f:/g/personal/ludovica_aisa_usc_es/EpsrPRNkn0VBv6R1z65D5yQBdNmmAbj2HtBOqFjAkHnWtA?e=37VO4K).
Next step is to test this rendering with a small system that has a clear secondary structure shape and these mentioned systems but restrained, to check if those issues happen or not.

**Comment by ludovicaisa** [comment]
Further going in potential visualitations issues: with PC-VR setup the cartoon rendering is different than with APK, I just uploaded images to the folder mentioned above.
I compared Narupa2 and Nanover running `neuraminidase.xml` from openmm notebook and Narupa2 doesn't show the dissolvation of the structure after resetting the system.

**Comment by Ragzouken** [comment]
All confirmed working for PC-VR, with the Quest standalones issued covered in https://github.com/IRL2/nanover-docs/issues/141 and https://github.com/IRL2/nanover-imd-vr/issues/47
