### ISSUE TITLE
Translate the CI from gitlab to github actions

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-server-py#2]
While moving the repository from [gitlab](https://gitlab.com/intangiblerealities/narupa-protocol) to here, we lost the continuous integration pipelines. These need to be restored so we can check the quality and validity of new contributions.

* [x] Run the tests for the python libraries on github actions (see PR #1)
* [x] Run the tests for the C# libraries on github actions (see PR #1)
* [ ] #3
* [x] #4
* [x] #5
* [x] #6
* [x] #7
* [x] #8

**Comment by Ragzouken** [comment]
Closing this as done since the minimum version thing is the only one outstanding and stands alone.
