### ISSUE TITLE
Update 17-alanine and nanotube from SubtleGame files

### ISSUE THREAD

**Issue by Mohamed-Dhouioui** [IRL2/nanover-server-py#297]
Harry says VelocityVerlet is not good for iMD systems because it has no thermostat, and the systems need to be equilibrated.

**Comment by hjstroud** [comment]
I suppose it depends exactly what you are trying to simulate, but with Velocity Verlet there is no way for the system to remove the excess energy added to it after the iMD interaction ends. This may be the behaviour we want in some cases, but my feeling is that we should think carefully about the sort of physics we want to simulate, and then choose the appropriate integrators for those systems, explaining what we are simulating in the accompanying descriptive files (that should be present in each directory that contains input files).
