### ISSUE TITLE
ASE double-calculates iMD force each simulation step

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-server-py#306]
This is related to issue #305: in the current implementation, ASE seems to calculate the iMD forces twice for each simulation step. This means that for a frame interval of 5 simulation steps, ASE calculates the iMD forces _10 times_, whereas the equivalent setup for raw OpenMM only calculates these forces _once_. We should make sure that ASE isn't redundantly re-calculating these forces each time the iMD forces are calculated.

**Comment by Ragzouken** [comment]
From discussing today: it seems that ASE `VelocityVerlet` dynamics needs to calculate forces twice due to the RATTLE algorithm adjusting positions (for constraints) during its course. But for us we want to explicitly control when interaction forces are calculated.
