### ISSUE TITLE
Nanover-OpenMM have issue in exchanging informations 

### ISSUE THREAD

**Issue by ludovicaisa** [IRL2/nanover-server-py#331]
I encountered an issue inizialising an iMD-VR session, specifically running a CHARMM simulation serving topology and parameters files, attached here.
[files.zip](https://github.com/user-attachments/files/18065056/files.zip)

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout, exit, stderr

psf = CharmmPsfFile('toppar/da.psf')
pdb = PDBFile('smd_ini.pdb')
params = CharmmParameterSet('toppar/top_all27_prot_lipid.rtf', 'toppar/par_all27_prot_lipid.prm')

system = psf.createSystem(params, nonbondedMethod=NoCutoff,
        constraints=HBonds,  hydrogenMass=1.5*amu)

restraint = CustomExternalForce('k*periodicdistance(x, y, z, x0, y0, z0)^2')
system.addForce(restraint)
restraint.addGlobalParameter('k', 3012.48*kilojoules_per_mole/nanometer**2)
restraint.addPerParticleParameter('x0')
restraint.addPerParticleParameter('y0')
restraint.addPerParticleParameter('z0')
restraint.addParticle(1, pdb.positions[1]) # add constrain to N

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(psf.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(DCDReporter('output1.dcd', 10))
simulation.reporters.append(StateDataReporter(stdout, 200, step=True, potentialEnergy=True, temperature=True))

simulation.step(1000)
```

Until this point everything is fine, I got a working dcd file and the energies and temperature of the system were quantitative comparable with an other simulated, but differently , deca alanine system from this [Openmm workshop](https://github.com/openmm/openmm_workshops/blob/41e1a8b3c3ba8ba9e9e8c747595f7b9c04a8aab3/section_2/custom_forces.ipynb#L25).

The problem arises when I want to run an OmniRunner simulation, at first it seemed that: "NanoVer is running over all the forces in the system and trying to update them, but OpenMM complains that one that we try to update has never been initialized yet." mentioning @Ragzouken. 
I repeated the procedure in this [pull request](https://github.com/IRL2/nanover-server-py/pull/327)'s environment and what I observed is that
 the complex's simulation is absent when connecting to its server with a VR client and, as expected, the output dcd obtained from OmniRunner is unreadable by VMD/Pymol.

**Comment by Ragzouken** [comment]
the files you added seem to be missing `top_all27_prot_lipid.rtf`, could you add it too?

**Comment by ludovicaisa** [comment]
[files.zip](https://github.com/user-attachments/files/18076708/files.zip)
Here it is, inside the zip
